export type CaseStudy = {
  id: string;
  title: string;
  architect: string;
  location: string;
  year: string;
  typology: string;
  region: string;
  scale: string;
  projectType: "文化" | "公共" | "居住" | "规划" | "景观";
  gradient: string;
  image: string;
  imageCredit: { label: string; url: string; license: string };
  short: string;
  principle: string;
  strategy: string;
  elements: string[];
  palette: { name: string; hex: string }[];
  sources: { label: string; url: string }[];
  risks: string[];
  tags: string[];
  context?: string;
  researchQuestions?: string[];
  materialNotes?: string;
}

export const cases: CaseStudy[] = [
  {
    id: "heydar-aliyev-centre",
    title: "Heydar Aliyev Centre",
    architect: "Zaha Hadid Architects",
    location: "Baku, Azerbaijan",
    year: "2012",
    typology: "文化中心",
    region: "中东",
    scale: "101,801 m²",
    projectType: "文化",
    gradient: "linear-gradient(135deg, #d9d2c8 0%, #8d918d 42%, #222a29 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0e/HEYDAR_ALIYEV_CENTER_INDOORS.%D7%97%D7%9C%D7%9C_%D7%A4%D7%A0%D7%99%D7%9E%D7%99_%D7%9E%D7%95%D7%93%D7%A8%D7%A0%D7%99_%D7%91%D7%9E%D7%A8%D7%9B%D7%96_%D7%94%D7%99%D7%99%D7%93%D7%A8_%D7%90%D7%9C%D7%99%D7%99%D7%91.jpg",
    imageCredit: { label: "Wikimedia Commons / CC0", url: "https://commons.wikimedia.org/wiki/File:HEYDAR_ALIYEV_CENTER_INDOORS.%D7%97%D7%9C%D7%9C_%D7%A4%D7%A0%D7%99%D7%9E%D7%99_%D7%9E%D7%95%D7%93%D7%A8%D7%A0%D7%99_%D7%91%D7%9E%D7%A8%D7%9B%D7%96_%D7%94%D7%99%D7%99%D7%93%D7%A8_%D7%90%D7%9C%D7%99%D7%99%D7%91.jpg", license: "CC0" },
    short: "连续曲面把广场、建筑和公共活动编织成一条可步行的地景。",
    principle: "通过连续的公共地面消解建筑与城市之间的边界，让文化建筑成为可进入的城市地形。",
    strategy: "将广场、入口大厅和主要公共空间组织成一条无台阶的流线，曲面外皮同时承担导向与识别。",
    elements: ["连续曲面", "公共地景", "无台阶动线", "白色外皮", "城市广场"],
    palette: [{ name: "骨白", hex: "#e6e0d4" }, { name: "石灰灰", hex: "#aaa79d" }, { name: "深影", hex: "#2f3735" }],
    sources: [{ label: "Zaha Hadid Architects 项目页", url: "https://www.zaha-hadid.com/architecture/heydar-aliyev-centre/" }],
    risks: ["连续曲面需要高精度节点与施工协同", "形式语言不能替代公共活动运营"],
    tags: ["公共地景", "流线", "连续曲面"],
    context: "项目把一座文化中心放在城市广场与公共活动之间，重点不只是建筑造型，而是重新定义进入、停留和穿行。",
    researchQuestions: ["公共地面如何变成建筑的一部分？", "连续流线如何服务不同强度的公共活动？"],
    materialNotes: "白色复合外皮、连续曲面、低视觉干扰的广场界面。",
  },
  {
    id: "maxxi",
    title: "MAXXI: National Museum of XXI Century Arts",
    architect: "Zaha Hadid Architects",
    location: "Rome, Italy",
    year: "2009",
    typology: "艺术博物馆",
    region: "欧洲",
    scale: "27,000 m²",
    projectType: "文化",
    gradient: "linear-gradient(145deg, #222322 5%, #5e665f 47%, #b7b9af 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/43/More_than_meets_the_eye_MAXXI_Roma_2015.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:More_than_meets_the_eye_MAXXI_Roma_2015.jpg", license: "CC BY-SA 4.0" },
    short: "多条交叉的展览路径让建筑成为可持续变化的空间框架。",
    principle: "让展览路径、城市流线和时间性的艺术事件共同塑造空间，而不是用单一轴线规定观看。",
    strategy: "用交叉、悬挑和上方采光带组织可变展厅，让不同尺度的展览在同一框架里切换。",
    elements: ["交叉流线", "采光带", "悬挑体量", "可变展厅", "黑白对比"],
    palette: [{ name: "炭黑", hex: "#202321" }, { name: "混凝土", hex: "#9a9c95" }, { name: "天光", hex: "#d9ddd4" }],
    sources: [{ label: "MAXXI 官方项目页", url: "https://www.maxxi.art/en/" }, { label: "Zaha Hadid Architects", url: "https://www.zaha-hadid.com/architecture/maxxi/" }],
    risks: ["复杂流线需要清晰的导视系统", "开放展厅对声学和运营要求较高"],
    tags: ["展览", "流线", "可变空间"],
    context: "MAXXI 面对的是艺术展示不断变化的问题，因此空间框架比固定展厅形状更重要。",
    researchQuestions: ["展览路径如何影响观看顺序？", "可变空间需要哪些导视和声环境条件？"],
    materialNotes: "混凝土、钢、黑色天花和顶部采光带共同形成方向感。",
  },
  {
    id: "vitra-fire-station",
    title: "Vitra Fire Station",
    architect: "Zaha Hadid Architects",
    location: "Weil am Rhein, Germany",
    year: "1993",
    typology: "消防站",
    region: "欧洲",
    scale: "852 m²",
    projectType: "公共",
    gradient: "linear-gradient(120deg, #1b2429 0%, #697472 40%, #d4c6b6 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Vitra_Campus_-_Hadid_Fire_Station_-_full_view%2C_blue_sky.jpg",
    imageCredit: { label: "Wikimedia Commons / CC0", url: "https://commons.wikimedia.org/wiki/File:Vitra_Campus_-_Hadid_Fire_Station_-_full_view,_blue_sky.jpg", license: "CC0" },
    short: "锐利的线性墙体把速度、警觉和队列感凝固成空间。",
    principle: "从行动状态出发组织建筑，使结构、动线和视觉张力服务于即时响应。",
    strategy: "用折线墙体定义开放的车辆场地和内部秩序，避免传统房间式分隔。",
    elements: ["折线墙体", "开放场地", "线性构件", "即时响应", "灰色混凝土"],
    palette: [{ name: "铅灰", hex: "#64706f" }, { name: "深蓝灰", hex: "#233038" }, { name: "暖砂", hex: "#c8b49c" }],
    sources: [{ label: "Zaha Hadid Architects 项目页", url: "https://www.zaha-hadid.com/architecture/vitra-fire-station/" }],
    risks: ["空间的开放性可能削弱后勤收纳效率", "强烈的形态需要明确的使用逻辑支撑"],
    tags: ["响应", "线性", "构造"],
    context: "消防站把即时响应作为首要任务，建筑的线性构件和开放场地都围绕行动速度组织。",
    researchQuestions: ["如何把运营逻辑转译为空间秩序？", "强烈形式如何避免干扰后勤效率？"],
    materialNotes: "灰色混凝土、折线墙体和连续地面共同构成紧张的线性空间。",
  },
  {
    id: "8-house",
    title: "8 House",
    architect: "BIG — Bjarke Ingels Group",
    location: "Copenhagen, Denmark",
    year: "2010",
    typology: "混合社区",
    region: "欧洲",
    scale: "62,000 m²",
    projectType: "居住",
    gradient: "linear-gradient(135deg, #81918e 0%, #c7c0ae 43%, #404d51 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/9/96/BIG_-_8_House.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:BIG_-_8_House.jpg", license: "CC BY 2.0" },
    short: "一条连续上升的公共路径把办公、商业和居住串成混合社区。",
    principle: "通过把不同功能混合在一条可步行的框架里，让日常活动共享空间价值。",
    strategy: "环形体量在不同角部抬升和压低，使住宅获得阳光与视野，底层商业面向街道。",
    elements: ["连续坡道", "混合功能", "内向庭院", "街道界面", "绿色屋面"],
    palette: [{ name: "苔藓绿", hex: "#81918e" }, { name: "沙色", hex: "#c7c0ae" }, { name: "深靛", hex: "#404d51" }],
    sources: [{ label: "BIG 官方项目页", url: "https://big.dk/projects/8-house-2021" }],
    risks: ["混合功能需要清楚的共享空间管理", "连续坡道的无障碍和排水必须同步设计"],
    tags: ["混合功能", "社区", "坡道"],
    context: "8 House 试图把办公、商业和居住放进同一个可步行的社区框架，研究重点是混合功能如何产生额外公共价值。",
    researchQuestions: ["混合功能如何共享公共空间？", "连续坡道如何同时承担社交、无障碍和交通？"],
    materialNotes: "砖、玻璃、绿色屋面和连续外部路径共同形成生活化的街区尺度。",
  },
  {
    id: "chichu-art-museum",
    title: "Chichu Art Museum",
    architect: "Tadao Ando Architect & Associates",
    location: "Naoshima, Japan",
    year: "2004",
    typology: "地下美术馆",
    region: "亚洲",
    scale: "地下场地",
    projectType: "文化",
    gradient: "linear-gradient(135deg, #d7d7cd 0%, #71807b 42%, #283535 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/c/c2/Chichu_art_museum02s2560.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 2.5", url: "https://commons.wikimedia.org/wiki/File:Chichu_art_museum02s2560.jpg", license: "CC BY 2.5" },
    short: "把大部分建筑埋入地下，让自然光成为展览体验的一部分。",
    principle: "以最小的地表干预保护场地自然性，并让光线、时间和艺术共同构成空间。",
    strategy: "用地下几何体量和天井引入自然光，组织作品、路径和季节变化之间的关系。",
    elements: ["地下体量", "天井", "自然光", "清水混凝土", "场地隐身"],
    palette: [{ name: "雾灰", hex: "#d7d7cd" }, { name: "苔绿", hex: "#71807b" }, { name: "深海", hex: "#283535" }],
    sources: [{ label: "Benesse Art Site 官方项目页", url: "https://benesse-artsite.jp/en/art/chichu.html" }],
    risks: ["地下空间依赖精准的采光、排水和防潮", "过度克制可能降低首次到访者的可识别性"],
    tags: ["场地", "自然光", "地下"],
    context: "Chichu Art Museum 把建筑大部分隐藏在地下，以最小的地表介入保护直岛环境，并让自然光参与作品体验。",
    researchQuestions: ["隐身的建筑如何保持公共可达性？", "自然光如何成为空间和展览的共同材料？"],
    materialNotes: "清水混凝土、天井、阴影和经过控制的自然光。",
  },
  {
    id: "harbin-opera-house",
    title: "Harbin Opera House",
    architect: "MAD Architects",
    location: "Harbin, China",
    year: "2015",
    typology: "歌剧院",
    region: "亚洲",
    scale: "79,000 m²",
    projectType: "文化",
    gradient: "linear-gradient(135deg, #d9e3e0 0%, #89999b 44%, #25343b 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/3/34/Harbin_Grand_Theatre_Pano_201609.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Harbin_Grand_Theatre_Pano_201609.jpg", license: "CC BY 2.0" },
    short: "流动的白色外壳回应寒地风景，把公共平台推向松花江。",
    principle: "把建筑看作被风和水塑形的地貌，让公共活动沿着外壳连续展开。",
    strategy: "以折叠的外皮包裹大小剧场，并把屋顶、广场和观景路径连接成公共地形。",
    elements: ["折叠外皮", "寒地回应", "公共屋顶", "水岸关系", "剧场声学"],
    palette: [{ name: "雪白", hex: "#d9e3e0" }, { name: "雾蓝", hex: "#89999b" }, { name: "江岸深灰", hex: "#25343b" }],
    sources: [{ label: "MAD Architects 项目资料", url: "https://www.i-mad.com/work/harbin-opera-house/" }],
    risks: ["寒地维护成本与结冰风险需要前置评估", "外壳复杂度会显著影响建造预算"],
    tags: ["寒地", "地貌", "公共屋顶"],
    context: "哈尔滨歌剧院把寒地滨水环境当作建筑的起点，公共路径、观景平台和剧场外壳被组织成连续地形。",
    researchQuestions: ["寒地气候如何改变公共空间的开放方式？", "复杂外壳如何同时承担识别与维护？"],
    materialNotes: "白色外壳、折叠表皮、石材和大尺度公共台阶。",
  },
  {
    id: "rolex-learning-centre",
    title: "Rolex Learning Center",
    architect: "SANAA",
    location: "Lausanne, Switzerland",
    year: "2010",
    typology: "学习中心",
    region: "欧洲",
    scale: "20,000 m²",
    projectType: "公共",
    gradient: "linear-gradient(135deg, #e8e2d3 0%, #a8b2aa 42%, #4e6268 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Rolex_Learning_center.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 3.0", url: "https://commons.wikimedia.org/wiki/File:Rolex_Learning_center.jpg", license: "CC BY-SA 3.0" },
    short: "连续起伏的地面把学习、交流、阅读和休憩放在同一个开放平面。",
    principle: "用连续而非分隔的空间支持不同强度的学习与社交，让公共性成为组织工具。",
    strategy: "以缓坡、天井和大跨度结构塑造开放平面，活动密度随着地形和光线变化。",
    elements: ["连续地面", "天井", "开放学习", "微地形", "柔性边界"],
    palette: [{ name: "纸白", hex: "#e8e2d3" }, { name: "雾绿", hex: "#a8b2aa" }, { name: "蓝灰", hex: "#4e6268" }],
    sources: [{ label: "EPFL 官方项目页", url: "https://www.epfl.ch/campus/visitors/en/rolex-learning-center/" }],
    risks: ["开放平面需要高质量声环境分区", "流动空间要有足够的家具和标识支撑使用"],
    tags: ["学习", "连续空间", "开放平面"],
    context: "Rolex Learning Center 把学习、交流和休息放在一个没有明确房间边界的连续平面中，公共性来自空间的可选择性。",
    researchQuestions: ["开放平面如何支持不同专注程度？", "微地形如何替代传统房间分隔？"],
    materialNotes: "浅色地面、柔性家具、天井和连续起伏的室内地形。",
  },
  {
    id: "sendai-mediatheque",
    title: "Sendai Mediatheque",
    architect: "Toyo Ito & Associates",
    location: "Sendai, Japan",
    year: "2001",
    typology: "媒体中心",
    region: "亚洲",
    scale: "21,682 m²",
    projectType: "公共",
    gradient: "linear-gradient(135deg, #d8d6ca 0%, #9caa9c 43%, #394e4c 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/1/14/Sendai_Mediatheque_2009.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 2.0", url: "https://commons.wikimedia.org/wiki/File:Sendai_Mediatheque_2009.jpg", license: "CC BY 2.0" },
    short: "树状结构管把不同媒介和公共活动叠合在一个透明框架里。",
    principle: "用基础设施而不是固定房间定义公共建筑，让信息、光线和人的流动保持开放。",
    strategy: "以十三根结构管承载设备、交通和环境系统，楼板保持尽可能自由的公共平面。",
    elements: ["结构管", "透明界面", "自由平面", "多媒体", "城市客厅"],
    palette: [{ name: "暖灰", hex: "#d8d6ca" }, { name: "叶绿", hex: "#9caa9c" }, { name: "墨绿", hex: "#394e4c" }],
    sources: [{ label: "Sendai Mediatheque 官方资料", url: "https://www.smt.jp/en/" }],
    risks: ["系统集成需要长期维护策略", "透明界面与开放结构对热舒适提出更高要求"],
    tags: ["基础设施", "媒体", "透明"],
    context: "Sendai Mediatheque 用结构管承载交通、设备和环境系统，让楼板保持自由，把建筑变成可持续变化的城市客厅。",
    researchQuestions: ["基础设施如何成为空间而不是隐藏在空间之后？", "透明开放的公共建筑如何处理热舒适和维护？"],
    materialNotes: "钢结构管、玻璃幕墙、自由平面和可变媒体设施。",
  },
  {
    id: "superkilen",
    title: "Superkilen",
    architect: "BIG + Topotek 1 + Superflex",
    location: "Copenhagen, Denmark",
    year: "2012",
    typology: "城市公园",
    region: "欧洲",
    scale: "线性公共空间",
    projectType: "景观",
    gradient: "linear-gradient(135deg, #d72f36 0%, #ec8a35 44%, #263d73 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/2_Superkilen_Park.jpg/1920px-2_Superkilen_Park.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:2_Superkilen_Park.jpg", license: "CC BY-SA 4.0" },
    short: "把多元社区的日常记忆转译成一条高辨识度的公共景观展览带。",
    principle: "把参与式设计从意见收集转成公共空间中的具体提案，让地方身份通过可使用的物件和活动被看见。",
    strategy: "以红、黑、绿三个空间段组织运动、停留和穿行，并把不同文化背景的城市物件放大为公共设施。",
    elements: ["参与式设计", "高饱和色彩", "城市物件", "运动场地", "线性公园"],
    palette: [{ name: "信号红", hex: "#d72f36" }, { name: "暖橙", hex: "#ec8a35" }, { name: "深蓝", hex: "#263d73" }],
    sources: [{ label: "BIG 官方项目页", url: "https://big.dk/projects/superkilen-1621" }],
    risks: ["符号化物件需要持续的社区维护和解释", "强烈色彩与活动密度不能替代遮荫、排水和安全等基础性能"],
    tags: ["参与式", "公共空间", "多元社区"],
    context: "Superkilen 位于哥本哈根 Nørrebro，是 BIG、Topotek 1 与 Superflex 协作完成的公共空间项目，重点研究多元社区如何形成共同的场所身份。",
    researchQuestions: ["社区参与如何转译为空间和设施？", "公共空间如何同时容纳地方记忆与日常运动？"],
    materialNotes: "彩色铺装、定制城市设施、运动场地和可识别的线性空间段落。",
  },
  {
    id: "high-line",
    title: "The High Line",
    architect: "Field Operations + Diller Scofidio + Renfro + Piet Oudolf",
    location: "New York, United States",
    year: "2009–2019",
    typology: "高架线性公园",
    region: "北美",
    scale: "城市线性公园",
    projectType: "景观",
    gradient: "linear-gradient(135deg, #d7d1b7 0%, #9ca98a 44%, #45595a 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/11th_Avenue_from_High_Line%2C_New_York_City%2C_20231001_1716_1455.jpg/1920px-11th_Avenue_from_High_Line%2C_New_York_City%2C_20231001_1716_1455.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 4.0", url: "https://commons.wikimedia.org/wiki/File:11th_Avenue_from_High_Line,_New_York_City,_20231001_1716_1455.jpg", license: "CC BY 4.0" },
    short: "保留废弃铁路的工业记忆，让自发生长的植物成为高架公共空间的设计线索。",
    principle: "不把旧基础设施清空重做，而是保留其结构和时间痕迹，把野生景观、城市漫游和公共项目叠合起来。",
    strategy: "用可穿行的铺装缝隙、分区种植和观景节点把原有铁路结构转成连续的步行公园，并通过运营和公共活动维持活力。",
    elements: ["基础设施再利用", "自然式种植", "连续漫游", "工业遗产", "公共运营"],
    palette: [{ name: "枯草金", hex: "#d7d1b7" }, { name: "种植绿", hex: "#9ca98a" }, { name: "钢结构灰", hex: "#45595a" }],
    sources: [{ label: "Field Operations 官方项目页", url: "https://www.fieldoperations.net/project/high-line" }, { label: "The High Line 官方网站", url: "https://www.thehighline.org/" }],
    risks: ["高人流和旅游化可能挤压周边社区的日常使用", "高架结构、种植维护和公共运营需要长期资金协同"],
    tags: ["再利用", "种植", "公共运营"],
    context: "High Line 的设计由 Field Operations、Diller Scofidio + Renfro 与 Piet Oudolf 协作完成，核心是把废弃高架铁路的工业遗产和自生景观转成可持续运营的城市公园。",
    researchQuestions: ["如何让基础设施的时间痕迹成为景观资源？", "景观设计怎样与长期公共运营共同工作？"],
    materialNotes: "保留铁路结构、混凝土铺装缝隙、自然式多年生植物和连续的观景路径。",
  },
  {
    id: "hammarby-sjostad",
    title: "Hammarby Sjöstad",
    architect: "Stockholm City + 多家事务所与基础设施团队",
    location: "Stockholm, Sweden",
    year: "1994–2020",
    typology: "可持续城市片区",
    region: "欧洲",
    scale: "滨水城市片区",
    projectType: "规划",
    gradient: "linear-gradient(135deg, #b7c8c0 0%, #718c8b 44%, #354b55 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Hammarby_Sj%C3%B6stad_January_2015.jpg/1920px-Hammarby_Sj%C3%B6stad_January_2015.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Hammarby_Sj%C3%B6stad_January_2015.jpg", license: "CC BY-SA 4.0" },
    short: "以滨水街区、混合功能和资源循环系统组织一套可观察的可持续城市模型。",
    principle: "把环境目标从单体建筑性能提升到街区尺度，让水、能源、废弃物、交通和日常生活互相联动。",
    strategy: "以半开放街区、滨水公共空间和混合功能建立城市骨架，再用资源循环和公共交通系统支撑片区运行。",
    elements: ["半开放街区", "滨水界面", "混合功能", "资源循环", "公共交通"],
    palette: [{ name: "水岸灰绿", hex: "#b7c8c0" }, { name: "雾青", hex: "#718c8b" }, { name: "深水蓝", hex: "#354b55" }],
    sources: [{ label: "Hammarby Sjöstad 官方资料", url: "https://www.hammarbysjostad.se/en/hammarby-sjostad/" }, { label: "Stockholm 城市发展资料", url: "https://vaxer.stockholm/omraden/stadsutvecklingsomraden/stadsutvecklingsomrade-hammarby-sjostad/" }],
    risks: ["街区级环境目标需要跨部门和跨周期的治理机制", "高品质滨水空间可能带来居住成本与社会公平问题"],
    tags: ["街区规划", "循环系统", "滨水"],
    context: "Hammarby Sjöstad 是斯德哥尔摩的重要城市更新片区，资料强调半开放街区、滨水视野、混合功能以及能源、水和废弃物之间的系统协同。",
    researchQuestions: ["环境目标如何落到街区空间与基础设施？", "滨水公共性如何与高密度开发共存？"],
    materialNotes: "砖与金属立面、滨水步行界面、街区绿地和可见的基础设施系统。",
  },
  {
    id: "cheonggyecheon-restoration",
    title: "Cheonggyecheon Stream Restoration",
    architect: "Seoul Metropolitan Government + 多学科设计团队",
    location: "Seoul, South Korea",
    year: "2003–2005",
    typology: "城市河流恢复",
    region: "亚洲",
    scale: "约 11 km 城市水系",
    projectType: "景观",
    gradient: "linear-gradient(135deg, #a8c8bd 0%, #4b918b 45%, #203f4a 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Cheonggyecheon_evening_2.jpg/1920px-Cheonggyecheon_evening_2.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0", url: "https://commons.wikimedia.org/wiki/File:Cheonggyecheon_evening_2.jpg", license: "CC BY-SA 4.0" },
    short: "把被覆盖的城市水系重新带回地面，重建首尔中心区的步行、水岸与公共生活。",
    principle: "把河流恢复作为城市更新和公共空间重组的入口，重新平衡机动车基础设施、历史记忆与日常亲水活动。",
    strategy: "拆除覆盖水系的基础设施，连续组织水岸步行空间、桥梁和城市节点，并通过分段处理适应不同的城市界面。",
    elements: ["水系恢复", "步行连续性", "桥梁节点", "城市更新", "亲水空间"],
    palette: [{ name: "水岸青", hex: "#a8c8bd" }, { name: "河流绿", hex: "#4b918b" }, { name: "夜色蓝", hex: "#203f4a" }],
    sources: [{ label: "首尔市政府清溪川资料", url: "https://english.seoul.go.kr/service/amusement/stream/1-cheonggyecheon/" }, { label: "首尔市政府项目说明", url: "https://english.seoul.go.kr/cheonggyecheon-stream-2/" }],
    risks: ["恢复后的水系依赖持续的水量、维护和公共安全管理", "大型更新项目可能改善公共空间但也会改变周边商业与居民结构"],
    tags: ["水系恢复", "城市更新", "步行"],
    context: "清溪川恢复项目在 2003 年启动、2005 年恢复开放，首尔市政府将其作为重新连接城市历史、水系和公共生活的城市更新项目。",
    researchQuestions: ["水系恢复如何改变城市公共空间的连续性？", "大型基础设施拆除如何转化为可感知的日常体验？"],
    materialNotes: "石材水岸、步行台阶、桥梁节点、连续水面和分段的城市界面。",
  },
  {
    id: "salk-institute",
    title: "Salk Institute",
    architect: "Louis I. Kahn",
    location: "La Jolla, United States",
    year: "1959–1965",
    typology: "生物研究机构",
    region: "北美",
    scale: "27-acre research campus",
    projectType: "公共",
    gradient: "linear-gradient(135deg, #e5ddd0 0%, #a5a39a 43%, #39464b 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Salk_Institute_2.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0 / Codera23", url: "https://commons.wikimedia.org/wiki/File:Salk_Institute_2.jpg", license: "CC BY-SA 4.0" },
    short: "两座研究楼围合出面向海洋的空庭，让光、尺度和科学协作共享一个秩序。",
    principle: "把研究空间做成可适应的基础设施，同时用一个克制而开放的庭院承载停留、交流与远景。",
    strategy: "以镜像体量、开放实验室和连续服务层组织研究功能，把天光引入实验空间，再用空庭将视线推向太平洋。",
    elements: ["镜像体量", "空庭", "自然采光", "开放实验室", "石材水渠"],
    palette: [{ name: "浅 travertine", hex: "#e5ddd0" }, { name: "混凝土灰", hex: "#a5a39a" }, { name: "海岸深蓝", hex: "#39464b" }],
    sources: [{ label: "Salk Institute 建筑介绍", url: "https://www.salk.edu/about/about-salk-architecture/" }, { label: "Salk Architecture Guide", url: "https://www.salk.edu/explore-salk-architecture-guide/" }],
    risks: ["高质量自然光需要与实验设备、遮阳和热环境共同校核", "强对称秩序可能掩盖不同研究团队对空间灵活性的差异"],
    tags: ["光与结构", "研究空间", "空庭"],
    context: "Salk Institute 是 Jonas Salk 委托 Louis Kahn 设计的研究园区，官方资料强调可适应的实验空间、两座镜像建筑和中央 travertine 庭院。",
    researchQuestions: ["自然光如何参与研究空间而不牺牲设备适应性？", "空庭怎样成为跨学科交流的基础设施？"],
    materialNotes: "混凝土、柚木、travertine 庭院、细窄水渠和顶部服务层。",
  },
  {
    id: "barcelona-pavilion",
    title: "Barcelona Pavilion",
    architect: "Ludwig Mies van der Rohe + Lilly Reich",
    location: "Barcelona, Spain",
    year: "1929 / 1986 reconstruction",
    typology: "展览 pavilion",
    region: "欧洲",
    scale: "small exhibition pavilion",
    projectType: "文化",
    gradient: "linear-gradient(135deg, #d8d5ca 0%, #8c9b9b 44%, #283b42 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/42/The_Barcelona_Pavilion%2C_Barcelona%2C_2010.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY 3.0 / Ashley Pomeroy", url: "https://commons.wikimedia.org/wiki/File:The_Barcelona_Pavilion,_Barcelona,_2010.jpg", license: "CC BY 3.0" },
    short: "自由平面、薄片墙体和反射水面把材料边界变成连续的观看经验。",
    principle: "不靠厚重体量制造纪念性，而是让比例、材料、反射和行走顺序共同构成空间。",
    strategy: "以独立墙片、悬挑屋面和不同材质的平面组织流线，让建筑在移动中不断改变边界和视线。",
    elements: ["自由平面", "薄片墙体", "悬挑屋面", "反射水面", "材料拼接"],
    palette: [{ name: "大理石灰", hex: "#d8d5ca" }, { name: "玻璃青", hex: "#8c9b9b" }, { name: "黑色钢柱", hex: "#283b42" }],
    sources: [{ label: "Fundació Mies van der Rohe 项目页", url: "https://miesbcn.com/the-pavilion/" }, { label: "Barcelona City 官方介绍", url: "https://www.barcelona.cat/en/discoverbcn/pics/el-pabellon-mies-van-der-rohe-96243111030" }],
    risks: ["材料与节点的精度要求很高，形式简洁不等于施工简单", "抽象的空间边界需要通过动线和维护保持清晰"],
    tags: ["材料", "自由平面", "比例"],
    context: "Barcelona Pavilion 是 1929 年巴塞罗那国际博览会德国馆的重建版本，Fundació Mies van der Rohe 负责其公共运营与研究。",
    researchQuestions: ["材料边界如何替代传统房间分隔？", "行走顺序如何参与空间构成？"],
    materialNotes: "大理石、玻璃、钢柱、浅水池和悬挑平屋面共同形成连续的材料场。",
  },
  {
    id: "kimbell-art-museum",
    title: "Kimbell Art Museum",
    architect: "Louis I. Kahn",
    location: "Fort Worth, United States",
    year: "1966–1972",
    typology: "艺术博物馆",
    region: "北美",
    scale: "museum building",
    projectType: "文化",
    gradient: "linear-gradient(135deg, #d5c6ad 0%, #9c9b91 45%, #3e4b50 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Fort_Worth_Cultural_District_June_2016_13_%28Kimbell_Art_Museum%29.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0 / Michael Barera", url: "https://commons.wikimedia.org/wiki/File:Fort_Worth_Cultural_District_June_2016_13_(Kimbell_Art_Museum).jpg", license: "CC BY-SA 4.0" },
    short: "重复的拱顶把结构、天光和观看节奏压缩成一套可复用的展厅原型。",
    principle: "让自然光成为博物馆的主要空间材料，用结构重复建立秩序，再以细微变化支持观看。",
    strategy: "以 cycloid vaults、顶部天窗和反射板过滤天光，使每个展厅拥有稳定但不僵硬的光环境。",
    elements: ["拱顶单元", "顶部天光", "反射板", "柱廊", "展厅节奏"],
    palette: [{ name: "暖石灰", hex: "#d5c6ad" }, { name: "混凝土银", hex: "#9c9b91" }, { name: "阴影蓝灰", hex: "#3e4b50" }],
    sources: [{ label: "Kimbell Art Museum 建筑页", url: "https://kimbellart.org/art-architecture/architecture/kahn-building" }, { label: "Kimbell Architecture 总览", url: "https://kimbellart.org/art-architecture/architecture" }],
    risks: ["自然采光的质量依赖天窗、反射板和收藏保护的协同维护", "重复拱顶容易被形式化复制，忽略了展览尺度和运营条件"],
    tags: ["天光", "结构重复", "博物馆"],
    context: "Kimbell Art Museum 官方将 Kahn 建筑描述为以光为主题的博物馆，顶部天窗与反射板共同把自然光转成柔和的展览照明。",
    researchQuestions: ["结构重复如何产生不同观看节奏？", "自然采光如何同时服务艺术保护与空间体验？"],
    materialNotes: "混凝土拱顶、travertine、木材、顶部天窗和反射铝板。",
  },
  {
    id: "therme-vals",
    title: "Therme Vals",
    architect: "Peter Zumthor",
    location: "Vals, Switzerland",
    year: "1996",
    typology: "温泉浴场",
    region: "欧洲",
    scale: "mountain thermal bath",
    projectType: "公共",
    gradient: "linear-gradient(135deg, #b9c4bc 0%, #69797a 45%, #2d3d43 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/4/43/Brutarchitekt_Therme_Vals.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0 / Brutarchitekt", url: "https://commons.wikimedia.org/wiki/File:Brutarchitekt_Therme_Vals.jpg", license: "CC BY-SA 4.0" },
    short: "以当地石材叠出一组嵌入山体的空间洞穴，让水、暗部和触感成为主要导视。",
    principle: "把建筑体验从视觉形象转向身体感知，让材料、温度、声音和路径共同构成场所。",
    strategy: "用石材模块和厚重墙体形成连续的池室、缝隙和光井，使人在明暗、冷热和开合之间移动。",
    elements: ["石材模块", "山体嵌入", "池室序列", "明暗转换", "身体感知"],
    palette: [{ name: "山灰", hex: "#b9c4bc" }, { name: "湿石青", hex: "#69797a" }, { name: "深水墨", hex: "#2d3d43" }],
    sources: [{ label: "7132 Therme 官方介绍", url: "https://vals.ch/en/enjoy/wellness/7132-therme/" }, { label: "Peter Zumthor 项目页", url: "https://zumthor.org/project/therme/" }],
    risks: ["高湿环境对石材、节点、防滑和维护提出持续要求", "沉浸式体验依赖运营和材料细节，不能只复制几何形式"],
    tags: ["材料感知", "山地", "空间序列"],
    context: "Therme Vals 由 Peter Zumthor 设计，项目把浴场嵌入山地环境，以石材、池水和光线建立缓慢而连续的身体体验。",
    researchQuestions: ["材料如何承担导视和空间叙事？", "沉浸式公共空间如何把运营条件转成设计资源？"],
    materialNotes: "当地石材、厚重墙体、温泉水、狭缝采光和多层次池室。",
  },
  {
    id: "benthemplein-water-square",
    title: "Benthemplein Water Square",
    architect: "De Urbanisten",
    location: "Rotterdam, The Netherlands",
    year: "2011–2013",
    typology: "海绵城市公共空间",
    region: "欧洲",
    scale: "urban water square",
    projectType: "景观",
    gradient: "linear-gradient(135deg, #8bc4c0 0%, #2f8b91 45%, #223c52 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Benthemplein_terrain_basket_gestion_eau.jpg",
    imageCredit: { label: "Wikimedia Commons / CC BY-SA 4.0 / Cathrotterdam", url: "https://commons.wikimedia.org/wiki/File:Benthemplein_terrain_basket_gestion_eau.jpg", license: "CC BY-SA 4.0" },
    short: "把暴雨调蓄设施做成篮球场、剧场和日常广场，让基础设施可见、可用、可参与。",
    principle: "把气候适应从隐藏的工程系统转成公共空间体验，使雨水管理成为城市生活的一部分。",
    strategy: "用分级下沉的场地、排水沟和多个蓄水池应对降雨；无雨时场地承担运动、停留和社区活动。",
    elements: ["下沉广场", "雨洪调蓄", "运动场地", "可见基础设施", "分级地形"],
    palette: [{ name: "水面青", hex: "#8bc4c0" }, { name: "运动蓝", hex: "#2f8b91" }, { name: "湿地深蓝", hex: "#223c52" }],
    sources: [{ label: "De Urbanisten 官方项目页", url: "https://www.urbanisten.nl/work/benthemplein" }, { label: "Public Space 项目资料", url: "https://www.publicspace.org/works/-/project/h034-water-square-in-benthemplein" }],
    risks: ["蓄水设施需要明确的安全、清洁和暴雨后恢复机制", "多功能场地若缺少社区运营，可能只剩下形式化的雨洪装置"],
    tags: ["雨洪", "气候适应", "公共空间"],
    context: "Benthemplein 是 De Urbanisten 设计的水广场，官方项目资料明确将公共空间和雨水存储作为一套双重策略。",
    researchQuestions: ["雨洪基础设施如何获得公共性？", "同一场地如何在晴天和暴雨中切换功能？"],
    materialNotes: "彩色硬质铺装、下沉混凝土场地、排水沟、运动设施和分级看台。",
  },
  {
    id: "vauban-freiburg",
    title: "Vauban District",
    architect: "Freiburg City + 多个社区与建筑团队",
    location: "Freiburg, Germany",
    year: "1990s–ongoing",
    typology: "低车化生态街区",
    region: "欧洲",
    scale: "约 38 ha urban district",
    projectType: "规划",
    gradient: "linear-gradient(135deg, #bfd2bb 0%, #779c7b 44%, #304c52 100%)",
    image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Vauban_Freiburg_13_06_52_381000.jpeg",
    imageCredit: { label: "Wikimedia Commons / CC0 / Shisma", url: "https://commons.wikimedia.org/wiki/File:Vauban_Freiburg_13_06_52_381000.jpeg", license: "CC0" },
    short: "把低车化、社区参与、能源目标和紧凑街区放进同一套长期治理框架。",
    principle: "可持续街区不只是建筑节能，而是由交通、土地、社区组织和能源系统共同塑造的生活方式。",
    strategy: "以紧凑的街区结构、分级道路和步行/自行车系统减少汽车依赖，再以合作建房和低能耗标准支持社区实施。",
    elements: ["低车化街道", "合作建房", "紧凑街区", "步行网络", "低能耗建筑"],
    palette: [{ name: "社区绿", hex: "#bfd2bb" }, { name: "树冠绿", hex: "#779c7b" }, { name: "道路深灰", hex: "#304c52" }],
    sources: [{ label: "Freiburg 市 Vauban 规划资料", url: "https://www.freiburg.de/pb/site/Freiburg/get/params_E-1604864046/647919/Infotafeln_Vauban_en.pdf" }, { label: "Freiburg 市 Vauban 街区介绍", url: "https://www.freiburg.de/pb/%2CLde_DE/208732.html" }],
    risks: ["低车化与停车管理需要持续治理，不能只依赖一次性设计", "生态与社区品牌可能推高地价，需持续评估社会公平和可负担性"],
    tags: ["街区治理", "低车化", "社区建造"],
    context: "Vauban 位于 Freiburg 的旧军营用地上，市政府资料强调紧凑街区、低车化交通、低能耗标准和社区参与的组合关系。",
    researchQuestions: ["交通政策如何转译为空间秩序？", "社区参与怎样影响街区建造和长期运营？"],
    materialNotes: "连续街区界面、低速住宅街道、步行和自行车网络、社区绿地及太阳能建筑。",
  },
];

const requiredCaseFields: (keyof CaseStudy)[] = ["id", "title", "architect", "location", "year", "typology", "region", "scale", "projectType", "image", "short", "principle", "strategy"];

export function validateCaseLibrary(items: readonly CaseStudy[] = cases) {
  const errors: string[] = [];
  const ids = new Set<string>();
  for (const item of items) {
    for (const field of requiredCaseFields) if (typeof item[field] !== "string" || !item[field].trim()) errors.push(`${item.id || "<unknown>"}.${field} 必须是非空字符串`);
    if (ids.has(item.id)) errors.push(`${item.id}.id 不能重复`);
    ids.add(item.id);
    if (!item.imageCredit?.url.startsWith("https://") || !item.imageCredit.license.trim()) errors.push(`${item.id}.imageCredit 必须包含 HTTPS 来源和许可`);
    if (!item.sources.length || item.sources.some((source) => !source.url.startsWith("https://") || !source.label.trim())) errors.push(`${item.id}.sources 必须包含带标签的 HTTPS 来源`);
    if (!item.elements.length || !item.palette.length || !item.risks.length || !item.tags.length) errors.push(`${item.id} 的 elements、palette、risks、tags 不能为空`);
    if (item.palette.some((color) => !/^#[0-9a-f]{6}$/i.test(color.hex))) errors.push(`${item.id}.palette 包含无效 HEX 颜色`);
  }
  if (errors.length) throw new Error(`案例数据校验失败：\n${errors.join("\n")}`);
  return { caseCount: items.length };
}

validateCaseLibrary();

export const taskTemplates = [
  { id: "principles", label: "提取设计思路", hint: "从一个案例里读懂它如何工作", prompt: "提取这个项目的核心理念、问题意识和空间策略，并标注每条判断的原始依据。" },
  { id: "elements", label: "识别设计元素", hint: "整理形态、动线、材料和界面", prompt: "拆解这个项目的体量、动线、材料、色彩和公共空间元素，输出可比较的结构化清单。" },
  { id: "compare", label: "比较案例", hint: "把不同项目放在同一个框架里", prompt: "比较三个案例在场地回应、公共性、空间组织和建造风险上的相同点与差异。" },
  { id: "palette", label: "提取颜色与材料", hint: "快速建立材料与氛围参考", prompt: "从原始案例资料中提取颜色、材质、光线和触感线索，并说明它们如何服务于空间体验。" },
  { id: "critique", label: "做一次方案批评", hint: "找出可迁移与不可复制的部分", prompt: "以建筑设计评审的方式，指出这个案例最值得借鉴的策略、潜在误读和实施风险。" },
  { id: "wishlist", label: "提出案例 Wish List", hint: "告诉社区下一步应该研究什么", prompt: "我希望看到更多关于某个建筑类型、地区、材料或设计策略的公开案例。" },
];

export const mcpTools = [
  { name: "search_cases", label: "检索案例", description: "按关键词、类型、地域和策略检索可追溯案例。" },
  { name: "get_case", label: "获取案例", description: "获取完整案例资料卡、设计元素、风险与来源。" },
  { name: "extract_design_elements", label: "提取设计元素", description: "返回结构化的理念、空间策略、元素和颜色。" },
  { name: "compare_cases", label: "比较案例", description: "用同一套字段比较多个案例，方便外部 Agent 继续工作。" },
  { name: "build_research_pack", label: "生成资料包", description: "输出可下载的 Markdown/JSON/README 研究资料包内容。" },
  { name: "list_case_facets", label: "浏览分类", description: "列出项目类型、地域、标签、元素和建筑师及其案例数量。" },
  { name: "match_cases_to_brief", label: "匹配研究任务", description: "用可解释的固定权重，把研究任务匹配到相关案例。" },
  { name: "build_case_collection", label: "生成案例集合", description: "汇总多个案例的比较字段、研究问题、风险和来源清单。" },
];

export function findCase(id: string) {
  return cases.find((item) => item.id === id);
}
